# Generated by Django 2.2.5 on 2019-09-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('security_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title_code_no', models.CharField(blank=True, db_column='Title_Code_No', max_length=250, null=True)),
                ('division_work_unit', models.CharField(blank=True, db_column='Division_Work_Unit', max_length=250, null=True)),
                ('levels', models.CharField(blank=True, db_column='Levels', max_length=25, null=True)),
            ],
            options={
                'db_table': 'JOB_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.IntegerField(db_column='Job_ID', primary_key=True, serialize=False)),
                ('agency', models.CharField(blank=True, db_column='Agency', max_length=250, null=True)),
                ('posting_type', models.CharField(blank=True, db_column='Posting_Type', max_length=250, null=True)),
                ('no_of_positions', models.IntegerField(blank=True, db_column='No_Of_Positions', null=True)),
                ('business_title', models.CharField(blank=True, db_column='Business_Title', max_length=250, null=True)),
                ('job_category', models.CharField(blank=True, db_column='Job_Category', max_length=250, null=True)),
            ],
            options={
                'db_table': 'JOBS',
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('civil_service_title', models.CharField(blank=True, db_column='Civil_Service_Title', max_length=250, null=True)),
                ('title_code_no', models.CharField(blank=True, db_column='Title_Code_No', max_length=250, null=True)),
                ('division_work_unit', models.CharField(blank=True, db_column='Division_Work_Unit', max_length=250, null=True)),
                ('phoneno', models.CharField(db_column='PhoneNo', max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TITLES',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('job', models.ForeignKey(db_column='Job_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='jobexp.Jobs')),
                ('full_part_time_indicator', models.CharField(blank=True, db_column='Full_Part_Time_indicator', max_length=10, null=True)),
                ('salary_range_from', models.IntegerField(blank=True, db_column='Salary_Range_From', null=True)),
                ('salary_range_to', models.IntegerField(blank=True, db_column='Salary_Range_To', null=True)),
                ('salary_frequency', models.CharField(blank=True, db_column='Salary_Frequency', max_length=30, null=True)),
                ('phoneno', models.ForeignKey(blank=True, db_column='PhoneNo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jobexp.Titles')),
            ],
            options={
                'db_table': 'SALARY',
            },
        ),
        migrations.CreateModel(
            name='LocTime',
            fields=[
                ('job', models.ForeignKey(db_column='Job_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='jobexp.Jobs')),
                ('work_location', models.CharField(blank=True, db_column='Work_Location', max_length=100, null=True)),
                ('residency_requirement', models.CharField(blank=True, db_column='Residency_Requirement', max_length=250, null=True)),
                ('posting_date', models.DateField(blank=True, db_column='Posting_Date', null=True)),
                ('posting_updated', models.DateField(blank=True, db_column='Posting_Updated', null=True)),
                ('phoneno', models.ForeignKey(blank=True, db_column='PhoneNo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jobexp.Titles')),
            ],
            options={
                'db_table': 'LOC_TIME',
            },
        ),
    ]
