# Generated by Django 2.2.5 on 2019-10-02 05:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('posting_loc', models.CharField(default='Bangalore', max_length=30)),
                ('requriments', models.CharField(max_length=1000)),
                ('job_type', models.CharField(blank=True, max_length=30)),
                ('posted_on', models.DateField(default=datetime.date.today)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('no_of_positions', models.IntegerField(default=1)),
                ('company', models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.Company')),
                ('rec_email', models.ForeignKey(db_column='rec_email', on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.Recuiter')),
            ],
            options={
                'db_table': 'JOBS',
            },
        ),
    ]
