# Generated by Django 2.2.5 on 2019-11-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_delete_applicantappliedjobs'),
        ('jobexp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantAppliedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.ApplicantProfile')),
                ('job_id', models.ForeignKey(on_delete=None, to='jobexp.Jobs')),
            ],
            options={
                'db_table': 'APPLICANT_APPLIED',
                'unique_together': {('email', 'job_id')},
            },
        ),
    ]
