# Generated by Django 2.2.5 on 2019-09-26 04:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobexp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('email_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('applicant_passwd', models.CharField(max_length=128)),
                ('signup_date', models.DateField(db_column='signUp_date', default=datetime.date.today)),
                ('first_nm', models.CharField(max_length=30)),
                ('last_nm', models.CharField(max_length=30)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'APPLICANT_PROFILE',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('biz_stream', models.CharField(blank=True, max_length=30)),
                ('website', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'COMPANY',
            },
        ),
        migrations.CreateModel(
            name='Recuiter',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=128)),
                ('company_name', models.ForeignKey(db_column='company_name', on_delete=django.db.models.deletion.DO_NOTHING, to='jobexp.Company')),
            ],
            options={
                'db_table': 'RECUITER',
            },
        ),
        migrations.DeleteModel(
            name='JobDetails',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='job',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='phoneno',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='business_title',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='posting_type',
        ),
        migrations.AddField(
            model_name='jobs',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='jobs',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='jobs',
            name='posted_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='jobs',
            name='posting_loc',
            field=models.CharField(default='Bangalore', max_length=30),
        ),
        migrations.AddField(
            model_name='jobs',
            name='requriments',
            field=models.CharField(default='be smart', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='title',
            field=models.CharField(default='Mgnr', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='no_of_positions',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ApplicantEdu',
            fields=[
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='jobexp.ApplicantProfile')),
                ('university', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cgpa', models.FloatField()),
            ],
            options={
                'db_table': 'APPLICANT_EDU',
            },
        ),
        migrations.CreateModel(
            name='ApplicantExp',
            fields=[
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='jobexp.ApplicantProfile')),
                ('total_exp', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'APPLICANT_EXP',
                'unique_together': {('email', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='ApplicantSkills',
            fields=[
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='jobexp.ApplicantProfile')),
                ('skill', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'APPLICANT_SKILLS',
                'unique_together': {('email', 'skill')},
            },
        ),
        migrations.DeleteModel(
            name='LocTime',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='Titles',
        ),
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(db_column='company', default='Google', on_delete=django.db.models.deletion.DO_NOTHING, to='jobexp.Company'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='rec_email',
            field=models.ForeignKey(db_column='rec_email', default='ash@gmail.com', on_delete=django.db.models.deletion.DO_NOTHING, to='jobexp.Recuiter'),
            preserve_default=False,
        ),
    ]
