# Generated by Django 2.2.5 on 2019-10-04 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobexp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='rec_email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.Recuiter'),
        ),
    ]
