# Generated by Django 2.2.5 on 2019-11-24 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobexp', '0002_applicantappliedjobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantappliedjobs',
            name='id',
        ),
        migrations.AlterField(
            model_name='applicantappliedjobs',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Accounts.ApplicantProfile'),
        ),
    ]
