# Generated by Django 2.2.5 on 2019-10-04 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobexp', '0002_auto_20191004_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='rec_email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
