# Generated by Django 2.2.5 on 2019-09-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobexp', '0002_auto_20190926_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.DO_NOTHING, to='jobexp.Company'),
        ),
    ]
