# Generated by Django 2.2.5 on 2019-12-08 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobexp', '0003_auto_20191124_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.CASCADE, to='Accounts.Company'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='rec_email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
