# Generated by Django 2.2.5 on 2019-09-28 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobexp', '0003_auto_20190927_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='first_nm',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='last_nm',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='signup_date',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date joined'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='password',
            field=models.CharField(default=2017, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='username',
            field=models.CharField(default='Admi', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
