# Generated by Django 2.2.5 on 2019-12-08 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobexp', '0004_auto_20191208_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantappliedjobs',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Accounts.ApplicantProfile'),
        ),
    ]
