# Generated by Django 2.2.5 on 2019-09-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobexp', '0004_auto_20190928_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='applicant_passwd',
        ),
    ]
