# Generated by Django 2.2.5 on 2019-09-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobexp', '0006_auto_20190928_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuiter',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
