# Generated by Django 2.2.5 on 2019-09-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobexp', '0007_auto_20190928_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='email_id',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='gender',
            field=models.CharField(max_length=30),
        ),
    ]
