# Generated by Django 2.2.5 on 2019-10-20 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'APPLICANT_PROFILE',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('biz_stream', models.CharField(blank=True, max_length=30)),
                ('website', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'COMPANY',
            },
        ),
        migrations.CreateModel(
            name='Recuiter',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('company_name', models.ForeignKey(db_column='company_name', on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.Company')),
            ],
            options={
                'db_table': 'RECUITER',
            },
        ),
        migrations.CreateModel(
            name='ApplicantEdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cgpa', models.FloatField()),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.ApplicantProfile')),
            ],
            options={
                'db_table': 'APPLICANT_EDU',
            },
        ),
        migrations.CreateModel(
            name='ApplicantSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.ApplicantProfile')),
            ],
            options={
                'db_table': 'APPLICANT_SKILLS',
                'unique_together': {('email', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='ApplicantExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exp', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company', models.CharField(max_length=30)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.ApplicantProfile')),
            ],
            options={
                'db_table': 'APPLICANT_EXP',
                'unique_together': {('email', 'start_date', 'end_date')},
            },
        ),
    ]
