# Generated by Django 2.2.5 on 2019-11-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicantAppliedJobs',
        ),
    ]
