# Generated by Django 2.2.5 on 2019-11-24 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_delete_applicantappliedjobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantedu',
            name='id',
        ),
        migrations.RemoveField(
            model_name='applicantexp',
            name='id',
        ),
        migrations.RemoveField(
            model_name='applicantskills',
            name='id',
        ),
        migrations.AlterField(
            model_name='applicantedu',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Accounts.ApplicantProfile'),
        ),
        migrations.AlterField(
            model_name='applicantexp',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Accounts.ApplicantProfile'),
        ),
        migrations.AlterField(
            model_name='applicantskills',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Accounts.ApplicantProfile'),
        ),
    ]
